variable "father_compartment_ocid" {}
variable "compartment_ocid" {}
variable "ssh_private_key" {}
variable "ssh_public_key" {}
variable "schedule_vars" {}
variable "tenancy_ocid" {}
variable "parent_group" {}
variable "gitlab_token" {}
variable "gitlab_list" {}
variable "fingerprint" {}
variable "user_ocid" {}
variable "region" {}